### ISSUE TITLE
Add and Commit your changes, then only PUSH

### ISSUE THREAD

**Issue by Arka-h** [AkshatBhat/Noteable#2]
# @AkshatBhat

**Comment by AkshatBhat** [comment]
The drawable folder contains images and the button styling XML. If you
require any of them contact me and I will send it. I have no idea why they
weren't uploaded. Also I have my apk release ready and can send it via
whatsapp but google sign in doesn't work. However the emulator and the app
installed on the phone(not apk) Google sign in works perfectly. If you have
why this happens please tell me!
